### ISSUE TITLE
./bin/importmap outdated command fails with undefined method `dig' for an instance of String 

### ISSUE THREAD

**Issue by ccasabona** [rails/importmap-rails#245]
Running ./binimportmap outdated fails with the following output:

```
./bin/importmap outdated
/Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:89:in `find_latest_version': undefined method `dig' for an instance of String (NoMethodError)

      latest_version = response.dig('dist-tags', 'latest')
                               ^^^^
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:26:in `block in outdated_packages'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `each'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `with_object'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `outdated_packages'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:78:in `outdated'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in `<top (required)>'
	from /Users/charlie/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/charlie/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/charlie/.rvm/gems/ruby-3.3.0@ruby3rails7turbostack/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
	from ./bin/importmap:4:in `<main>'
```

Ruby 3.3.0
Rails 7.1.3
System: MAC 10.15.7

**Comment by vietqhoang** [comment]
I am experiencing the same issue.

```
/Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:89:in `find_latest_version': undefined method `dig' for "version not found: dom":String (NoMethodError)

      latest_version = response.dig('dist-tags', 'latest')
                               ^^^^
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:26:in `block in outdated_packages'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `each'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `with_object'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/npm.rb:17:in `outdated_packages'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:78:in `outdated'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/importmap-rails-2.0.1/lib/importmap/commands.rb:141:in `<main>'
        from <internal:/Users/viet/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/viet/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/viet/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from ./bin/importmap:4:in `<main>'
```

I've identified the problematic pin which returns the String response:

```
pin "@floating-ui/utils/dom", to: "@floating-ui--utils--dom.js" # @0.2.1
```

Removing the line executes the `outdated` command successfully.

**Comment by ccasabona** [comment]
That is interesting.  I found that if I take out these 2 pins, the command works:

pin ***@***.***/turbo', to: ***@***.***' # @7.2.5
pin ***@***.***/actioncable/src', to: ***@***.***' # @7.0.4

**Comment by vietqhoang** [comment]
I submitted https://github.com/rails/importmap-rails/pull/246 which goes over the problem and proposed a first solution.

**Comment by coder2000** [comment]
It looks like the npmjs registry doesn't like package names that are more than one folder deep.

**Comment by drale2k** [comment]
I have the same issue with the following pin `pin "cross-fetch/polyfill", to: "cross-fetch--polyfill.js"`
