### ISSUE TITLE
test fails on NoMethodError content_security_policy_nonce

### ISSUE THREAD

**Issue by olleolleolle** [rails/importmap-rails#30]
Perhaps a require "action_dispatch/http/content_security_policy" or something, somewhere?

```
Importmap::ImportmapTagsHelperTest#test_javascript_inline_importmap_tag:
NameError: undefined local variable or method `content_security_policy_nonce' for #<Importmap::ImportmapTagsHelperTest:0x000055fa425cbda8>
    /home/runner/work/importmap-rails/importmap-rails/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.1/lib/action_dispatch/testing/assertions/routing.rb:187:in `method_missing'
    /home/runner/work/importmap-rails/importmap-rails/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.1/lib/action_view/test_case.rb:273:in `method_missing'
    /home/runner/work/importmap-rails/importmap-rails/app/helpers/importmap/importmap_tags_helper.rb:16:in `javascript_inline_importmap_tag'
    /home/runner/work/importmap-rails/importmap-rails/test/importmap_tags_helper_test.rb:7:in `block in <class:ImportmapTagsHelperTest>'

rails test /home/runner/work/importmap-rails/importmap-rails/test/importmap_tags_helper_test.rb:4
```

**Comment by dhh** [comment]
👍
